language: go

go:
  - 1.9.x

services:
  - docker

script:
  - export REPO=threestup/aporosa
  - export TAG=latest
  - export WILL_DEPLOY=`if [[ $TRAVIS_TAG != "" ]]; then echo "YES"; elif [[ $TRAVIS_BRANCH == "master" ]]; then echo "YES"; else echo "NO"; fi`
  - docker build -t "$REPO:$TAG" .

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - if [[ $WILL_DEPLOY == "YES" ]]; then
    if [[ $TRAVIS_TAG != "" ]]; then
    docker tag "$REPO:$TAG" "$REPO:$TRAVIS_TAG";
    docker push "$REPO:$TRAVIS_TAG"
    fi
    docker tag "$REPO:$TAG" "$REPO:build-$TRAVIS_BUILD_NUMBER";
    docker push "$REPO:$TRAVIS_BUILD_NUMBER";
    docker push "$REPO:$TAG";
    fi

env:
  global:
  - secure: Y9rcwbjyQqOG9pMeT/tCYGNwJLEkebX1B+Oj3sHXmqa/GGrBeFXB6glTn4Vzb5yo1Os9W/fDHsl9FYqiZSa7CIB2Mmqc41WjXQPG8bWJUXdPzmS2JdDDEnyHv3xuOB53qS/bA28vWPCyFEUh4H1JPu2Q8u6dKXZTx54AlOp1z4RU/bLXoceqy0jQy1vDOdsyyFBRpUnpumtSrIyBan/WuyTKY/tPj5HGyQUY2+6C/PbAHU/vGh0Pz5hn+5XkWZO7JJAbCEqzrNvXiEgsLo/GSbaDgHY3WlpCcVmW0UJIbil3Bx5tLrvz+ECUrEEbad4EukpbFb3mQem8Sjz5VMzAMt67Zrwn0E13VzUAycTkowKy0/z90zxhjkIx5KR8q2RyTVJBhxsu1Ko07JaDG3qLUyt4A7GJOq6uIw6Zsx8p6SUIn5d+Doxlcs/XeqbkUSpMJ/PrdLIpZq24ycLL8Fr+ZZsMbFHBBlnRzPFOadvp50PzpK6znhDO0SX4UGaiB+jYu7EncPMXJPHlqQ8lPRHftQuR7xe9S5bl28hKv+0iGWw4UwRe9gzqXJoNzIgx1mgdhab9HxvpTodfGaWd1NpQIDasq2bMhok2B2s3raE+3ybPMnT/ctbMkaJMLMnFpbSmXkzSwgkmN6VpTMJiYK1pgLxM0L555+lzPo9f3bQMOc4=
  - secure: kk4EeTrZV/4CLQB98xERW3ZxyQO1hBfAMXa6qe+54tZZEYOrhUhwCI/i9a+1yFMDu6ul2+idag05fkfMVyV0OHKUhY3kZAX5s6x17KJE+VkQ0XR0oepIA/7BdCfTw/wreWTcr076PqYd1hM0cNShIbRQM/cMUCQqFX2ocaLiAa9U0218yLdbmX5xVK/cKdD7Dq2qrcqzWFuj2BblneMfTuc/0seSzVnbXhI8jAqmiMJqFz08/lErklAdVeoVo5yjkY8e8xIxQvwKzjRI9APu+ktgMJDYwQc/riRJSnjkqS9UEyEj1B4dCpFMDiR9XH2gHNI2ibOIaUbSdI4k1C57wFYBN84LwMYFGNJNk3g2ti3HPNvhl/2rJvZaQ5Cqs+GFzm8QveMY6Kgo+e65e+LPvyIS26rgUShnvpCOKlKg/fszbnx5p0ooIJq/ynpqQbl3iEKQfEb0j+WOPfBxj7gzCmLBIrzWZl9LHeWTfsLeRvEfH8nUFzZkXZHYEXJV/DODjQnfwkojj4d0igGFU8lZ+2b6yPkrfQdel0mS9qQnUiNAqGjR8PWfynWAKcSSoMfsdgidSKi3k7c0apxqFBJ0KNWmIBtEH6cEkghDLpPvWGdKu/0O6FJoN6Ltx9SOhOuBDOB7liZs5UlIbdyMEibjnMMeRKzmx4e3vhKYRfh10KY=
